### ISSUE TITLE
Mudança de Dupla

### ISSUE THREAD

**Issue by agsaionara** [jfelipemm/cet058#1]
Professor queríamos informar que a nova dupla é Saionara Aguiar Gomes e Jesulino Felipe e esse é o nosso repositório. E queremos tbm que o senhor de uma olhada no nosso arquivo python.py para ver se estamos indo no caminho certo. Ps.: Ainda falta algumas coisas as serem implentadas

**Comment by jfelipemm** [comment]
Manda no repositório do professor
